### ISSUE TITLE
#83 Test video feed fixes work for py3 ocv3

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#100]
Testing changes in #100. Branch issue#83s4 has old haar files with a new image.py and Zane and myself has tested these changes. They still work for me, but I get the V4L error still. Would like more test results!

I tested in Fedora 21 using OpenCV3 (without OpenCL) and python3 using the updated image.py and old haar files provided by Trevor.

**Comment by SClawz** [comment]
As I said in issue#89:

Just tested a bunch and here's what we got: (done on cs lab pc 2nd from left)

-With opencl
Everything works fine. Video, color, and tracking. It is a bit laggy, and we still get the v4l error, but it works much better than it did.

-Without opencl
No difference, everything worked just as above

Everything was done with python 3.

**Comment by SClawz** [comment]
Can some others test this as well?

Look in the issue in the description, and pull that branch.

You need to do a test with opencl, and one without. you need to re-install opencv in order to do this with Kevin's tutorial: https://blog.kevinbrown.in/programming/2014/09/27/building-and-installing-opencv-3.html

to uninstall it, type sudo make uninstall in the release folder, and then 'make clean'. That should get you to the state in Kevin's tutorial right after you make the release directory and go into it.

Follow Tyler's PYTHON command (in #100) to turn off opencl when you re-install opencv.

Again, worked for me... Does this fix it for everyone else?

**Comment by kcarriere** [comment]
I'll try this now and post my results

**Comment by kcarriere** [comment]
What is the command for disabling OpenCL? I'm not seeing it in this issue

**Comment by WilliamAgoh** [comment]
testing updated image.py and old haar files provided by Trevor to see if the core dump error disappear and try to compare the code with our old code.

**Comment by WilliamAgoh** [comment]
@kcarriere take a look at the tutorial that tyler made issue#110

**Comment by kcarriere** [comment]
Ah, thank you. I'll try this again when I get a chance

**Comment by ashleyredzko** [comment]
Try this with OpenCL enabled, report on that and if you run into issues with it, try the fix listed in #110

**Comment by tommanolakis** [comment]
I tested everything out with OpenCL and without it and I got the same results as Zane posted above, no difference with OpenCL off.

**Comment by tnormoyle** [comment]
I tested it and still got the V4L error initially, but the video feed was working properly and feature detection seemed to be working fine. The results were still the same with and without OpenCL.

**Comment by kcarriere** [comment]
Finished testing. Along with others, I'm getting the V4L error with and without OpenCL. After a while, detection seems to kick in, but can take around a minute or so, and is pretty buggy and inconsistent.

**Comment by WilliamAgoh** [comment]
Just finish testing the new branch and I have the same result that you guys got. for instance, I have the same result with Open CL  ON or OFF. But the detection seems a little buggy but overall is pretty much stable. Now I am goinf to test opencv-3.0 beta
