### ISSUE TITLE
#117 Identify Plugins

### ISSUE THREAD

**Issue by TrevorBreton** [Mousers/mousetrap#151]
Identify plugins, what they do and how they work.

**Comment by TrevorBreton** [comment]
Will be in the lab tomorrow afternoon to start working on identifying and describing the plugins.

**Comment by tommanolakis** [comment]
So it seems there are 5 different plugins.

1.) Camera
2.) Display
3.) Nose
4.) Eyes
5.) Vision

The camera plugin is responsible for loading in the webcam so that it can read the users image.

The display plugin is responsible for writing the users image onto the screen so that the user can see their own image.

The nose plugin is responsible for detecting the users nose and uses the users nose as a point to detect movement.

The eyes plugin is responsible for detecting the users eyes and it can detect motion of the eyes, check whether or not an eye has been closed and has a class to detect the users left eye.

Finally, the vision plugin seems to correspond with OpenCV which also loads in the haar files, the camera,  and the feature detectors.

Maybe someone can look this over to see if I missed anything so they can add to it.

**Comment by TrevorBreton** [comment]
Results back in #117
