### ISSUE TITLE
744352: Create dependency install script for Fedora 21 with Python 3 and OpenCV3 (closes #20)

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#17]
Closes:
- https://bugzilla.gnome.org/show_bug.cgi?id=744352
- https://bugzilla.gnome.org/show_bug.cgi?id=737295

**Comment by JESchulz** [comment]
This comment is a reminder as to what was desired for the sprint for 2/23:
- Change the directory of the script.
- Update README.md install instructions to include this script.

**Comment by StoneyJackson** [comment]
Worked for me :)

**Comment by StoneyJackson** [comment]
Additional feedback...

I was confused as to what to pass as an argument for the script. I interpreted it as "the directory in which the opencv source will live". So I gave it `../opencv`. I.e., "please put opencv in a sibling directory named opencv. But then it just created a directory in my current directory called opencv. I checked the script. The script assumes the specified directory exists and doesn't create it if it doesn't. In fact, it just silently fails and continues the process.

My recommendation... rather than beat your head on making this extra feature work, just assume that the script is ran in the project root (do a quick test to check that it is: e.g., `if [ ! -e README.md -o ! -e configure.ac ] ; then echo "Please run from the project root" ; exit 1 ; fi`). Then opencv will be checked out into a subdirectory of the project root named opencv. That seams pretty harmless (famous last words). In general, go for the easiest implementation with the fewest moving parts that solves the problem. We can always add more later, if needed.

**Comment by collaj** [comment]
I was looking over your comment and I understand what you are asking but I was curious about one thing.  If opencv was downloaded and put in a subdirectory of the mousetrap project, wouldn't it get pushed up to github and clutter  our repository.  Couldn't I have opencv download to the same directory that mousetrap is in instead of making a subdirectory in mousetrap to avoid any confusion it might make for people developing and testing.

**Comment by StoneyJackson** [comment]
Ah. Good point. You probably shouldn't go outside the project directory (that's not very well manored). The project directory is our workspace.

How about this? Have your script create a `vendor/` subdirectory if it doesn't exist, and then clone opencv into `vendor/opencv`. Then add the following rule to `.gitignore`:

```
/vendor
```

This will prevent the vendors subdirectory of the project root from being included in the repo.

`vendor/` is a fairly common convention. It is used to store 3rd party code/libraries/etc.

**Comment by collaj** [comment]
Thank you.  I just ran into another problem.  I added the `set -e` and it is conflicting with another command.  I'm using `rpm` to install one of the dependencies from a URL but if that dependency is already installed the command returns 1 which causes the script to exit immediately with `set -e`.  I'm sure how to go about handling this because having that option enabled is good if the script gets hung up anywhere when executing but it cause the script to fail under a partial install of the dependencies.

**Comment by StoneyJackson** [comment]
With `set -e` if a command exits non-zero your script exits immediately with the same value. However, there are exceptions to this rule ([checkout -e on this page](http://www.tldp.org/LDP/abs/html/options.html)). One exception is if the command is part of a [list construct](http://www.tldp.org/LDP/abs/html/list-cons.html#LCONS1). You can take advantage of this to ignore the failure of a command if you know it might fail, and you are OK with that. Here's how I like to do it.

```
# Define a function that you'll use to ignore acceptable failures
ignore_failure() {
  return 0
}

rpm that might fail || ignore_failure
```

You could also do something like this (tests are immune to `set -e` too):

```
if ! possible_bad_command ; then
    echo "the command failed, but we don't care... :P"
    # or maybe do something about the problem instead :)
fi
```

You're becoming an expert bash scripter!

**Comment by StoneyJackson** [comment]
Or if you need the exit code of the possibly failing command, checkout http://stackoverflow.com/questions/9629710/proper-way-to-detect-shell-exit-code-when-errexit-option-set
