### ISSUE TITLE
As a user, I want the ability have MouseTrap track a bright object other than my forehead so that I can have increased flexibility of cursor movement.

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#22]
https://bugzilla.gnome.org/show_bug.cgi?id=667183

**Comment by adamdevigili** [comment]
https://github.com/adamdevigili/iControl

**Comment by HeidiEllis** [comment]
So what is the context of this code?  What is Control? And what does this do?  Providing some description of what this is doing would significantly help the understandability of the project and also make it much more likely that people would look at and perhaps incorporate your code. 

Also, this should go on Bugzilla which would also make it visible to the MouseTrap community so that they could evaluate your solution.

**Comment by adamdevigili** [comment]
Details on the project and how it works are detailed in the README.md file.

**Comment by HeidiEllis** [comment]
I understand the project, but what is this?? What does it contribute to the project? Why should I click on the link?

**Comment by adamdevigili** [comment]
Because is directly relates to this ticket, #22.
