### ISSUE TITLE
Testing #51 via VM Software

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#62]

**Comment by max12187** [comment]
This is how to get virtual box to forward a web cam to a VM: http://askubuntu.com/questions/4875/use-my-webcam-with-ubuntu-running-in-virtualbox

Note this requires the virtual box extension pack: https://www.virtualbox.org/wiki/Downloads

**Comment by max12187** [comment]
I ran the script on a fresh vm and got this error: https://www.dropbox.com/s/bjy9ep6lep4hwod/vm_script_error.png?dl=0

**Comment by tommanolakis** [comment]
I've gotten this error when trying to use Python 3 and OpenCV 3 on Ubuntu 14.04. The error is because the Python 3 library cannot find where OpenCV 3 is in the directory because it isn't linking correctly from what I read on some forums. When OpenCV 3 is installing it might not link some of the required static libraries, I couldn't find a fix for it.

**Comment by max12187** [comment]
Well, I ran the script a second time and it worked. There might of been a connection issue on the first run but i don't know. I'm going to do more investigating.

**Comment by StoneyJackson** [comment]
Hmm... I've got a different read of that error. The error in the screen shot looks like the cloning of opencv failed. Then the script tried to change into the directory that would have been created by the cloning. But since the cloning failed, the `cd` failed.

That the script worked the second time you tried it could have to do with your connection, or possibly something went wrong on opencv's side. It's hard to say.

**Comment by max12187** [comment]
So I installed the VM on my other machine and ran the script. I got a different error this time: https://www.dropbox.com/s/z8i214ossqvro4d/vm_error2.png?dl=0
Looks like the download for one of the dependencies timed out. I'm going to run it again and see what happens.

**Comment by max12187** [comment]
I ran the script a second time and I worked...

**Comment by max12187** [comment]
Testing the script on a VM keeps giving me problems. I suggest that some else try testing the script on a VM to see if its not just me.
