### ISSUE TITLE
Test #51 Under Partial or Incorrect Dependency Installs

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#77]
This is designed to stress test how the script performs while certain dependencies have been previously installed but not all of the dependencies have.

**Comment by JESchulz** [comment]
I found I'm getting a Mousetrap core dump issue when incorrect dependencies are installed previously such as Python 2.7 + OpenCV 2.

**Comment by max12187** [comment]
The script is designed to correctly install mousetrap dependencies. Whether or not mousetrap runs is irrelevant, as long as the dependencies work. So instead of running mousetrap, test to see if Open CV2 can be imported in python 3.

**Comment by JESchulz** [comment]
I should have clarified that the core dump was occurring even when the camera was not targeting the face as it normally doesn't do so when there is no facial target.

**Comment by andrewgalisa** [comment]
hey guys so I just ran the script on my local machine and it seemed to work. Just a quick question..was this script supposed to install Python3 as well because it seems like my machine is still running python 2.7...I know this was just for the dependencies so I'm assuming no but I just wanted to check
